### ISSUE TITLE
Login Title

### ISSUE THREAD

**Issue by rodrigok** [SPIRIT-21/cordova-plugin-1password#1]
Why there is no option to set the login title?

**Comment by RaphyFischer** [comment]
Hey there,

thanks for using our little plugin:)
I've already fixed this. I only need the ability to commit it to the repo. 
After this commit you are able to pass a title and a section title in "storeLoginForUrl" function of the JacaScript interface.

I hope this will solve your issue.
The issue will be closed as soon as the commit gose online:)

Kind regards

**Comment by rodrigok** [comment]
Awesome @Raphy1302, what about open a PR with your changes?

**Comment by RaphyFischer** [comment]
@rodrigok 
I've created a pull request.
unfortunately I was not able to test it. It should work, because the changes are not that complicated. 
Maybe you could give me some feedback as soon as the commit is included.

**Comment by RaphyFischer** [comment]
@rodrigok 
The commit is online!

**Comment by schnti** [comment]
The new version is published to npm.

**Comment by rodrigok** [comment]
Thanks
